version: '3.8'

services:
  frontend:
    image: manul95/foodgram-frontend:master
    volumes:
      - ./frontend:/app/result_build/

  db:
    image: postgres:latest
    restart: always
    volumes:
      - db_vol:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: manul95/foodgram-backend:master
    restart: always
    volumes:
      - ../data/:/data/
      - static_vol:/app/static/
      - media_vol:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/includes:/etc/nginx/includes/
      - ./certbot/www:/var/www/certbot/
      - ./certbot/conf/:/etc/nginx/ssl/
      - ./frontend/build/:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_vol:/var/html/static/
      - media_vol:/var/html/media/
    depends_on:
      - frontend
      - backend
  
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/
      - ./certbot/conf/:/etc/letsencrypt/

volumes:
  db_vol:
  static_vol:
  media_vol:
  
  
